### ISSUE TITLE
5 tests failing

### ISSUE THREAD

**Issue by runephilosof** [Esri/geoservices-ruby#2]
In the Readme.md it says the tests are run with `rake rspec`, but it is either `rake spec` or `rake test`.
The result is:

```
F....F.FFF

Failures:

  1) Geoservice getting a catalog should have services
     Failure/Error: @nhss_shakemaps = @catalog["nhss_shakemaps"]
     NoMethodError:
       undefined method `[]' for nil:NilClass
     # ./lib/geoservices/service/catalog.rb:18:in `block in []'
     # ./lib/geoservices/service/catalog.rb:17:in `each'
     # ./lib/geoservices/service/catalog.rb:17:in `[]'
     # ./spec/geoservices/catalog_spec.rb:7:in `block (3 levels) in <top (required)>'

  2) Geoservice getting a feature service should be countable
     Failure/Error: expect(@service.count(0)["count"]).to eq(1374)

       expected: 1374
            got: 1376

       (compared using ==)
     # ./spec/geoservices/service_spec.rb:22:in `block (3 levels) in <top (required)>'

  3) Geoservice getting a map service should have a mapName
     Failure/Error: expect(@service.metadata["mapName"]).to eq("Layers")

       expected: "Layers"
            got: nil

       (compared using ==)
     # ./spec/geoservices/service_spec.rb:33:in `block (3 levels) in <top (required)>'

  4) Geoservice getting a map service should have layers
     Failure/Error: expect(@service.layers.length).to eq(2)

       expected: 2
            got: 0

:/home/rp/.rbenv/versions/2.1.2/bin/ruby -I/home/rp/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-support-3.1.2/lib:/home/rp/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.1.7/lib /home/rp/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.1.7/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
       (compared using ==)
     # ./spec/geoservices/service_spec.rb:36:in `block (3 levels) in <top (required)>'

  5) Geoservice getting a map service should have layer index
     Failure/Error: expect(@service.layers[0]['name']).to eq("Watches/Warnings")
     NoMethodError:
       undefined method `[]' for nil:NilClass
     # ./spec/geoservices/service_spec.rb:39:in `block (3 levels) in <top (required)>'

Finished in 5.45 seconds (files took 0.22238 seconds to load)
10 examples, 5 failures
```

**Comment by ajturner** [comment]
thanks for checking this - I'll take a look (or PR accepted if you discover the issue).
